### ISSUE TITLE
Display estimated time indication for queue

### ISSUE THREAD

**Issue by canihavesomecoffee** [canihavesomecoffee/sample-platform#17]
Clone of canihavesomecoffee/ccx_gitbot#4

Currently the test page (for a given id) just displays

```This test is still in the queue! Please check again later.```

This should be improved to show how many other tests are in the queue before you, and it should also show an estimate of how long that'll take before the test gets started (we have start + end time available of previous tests)

Expected: a PEP-8 compliant PR.

**Comment by canihavesomecoffee** [comment]
Worth 1 point for GSoC Quali.

**Comment by madan96** [comment]
Hi. I would like to work on this issue. I have a one doubt. For the pending tests, will we be predicting their time based on previous data?

**Comment by canihavesomecoffee** [comment]
That's the idea, yes. That way an estimated end/completion of the queued test can be shown to the user. Ideally we calculate the average on the last x tests, and store that in the GeneralData table (so we don't have to recalculate the average every time the user opens the page).

**Comment by saurabhshri** [comment]
Also, it will be great if for currently running test we can know

`no_of_sub_tests_remaining/total_no_of sub_tests`.

Maybe in future sometime. :)

**Comment by divyanshshukla13** [comment]
Not able to replicate this. When I upload a sample, it displays no such text.  @canihavesomecoffee

**Comment by canihavesomecoffee** [comment]
Sample != Queued test
