### ISSUE TITLE
Add more logging when building fails

### ISSUE THREAD

**Issue by canihavesomecoffee** [canihavesomecoffee/sample-platform#2]
When a build fails (e.g. https://sampleplatform.ccextractor.org/test/147) , there's no logs indicating why the build fails. This should be improved.

**Comment by saurabhshri** [comment]
@canihavesomecoffee I was looking into the code to see if I can help in adding more logs. 

Apparently it uses "./build" located at https://github.com/CCExtractor/ccextractor/blob/master/linux/ to build CCExtractor. 

So the logging part would be done in that repository, right?
I have sent you a DM on Slack regarding the same.

**Comment by canihavesomecoffee** [comment]
Closed through #6

**Comment by canihavesomecoffee** [comment]
Worth 1 point for GSoC Quali.
