### ISSUE TITLE
While showing difference,sometimes last lines are ignored.

### ISSUE THREAD

**Issue by saurabhshri** [canihavesomecoffee/sample-platform#27]
Here: 

![1st](https://cloud.githubusercontent.com/assets/12415700/21745980/82759a66-d55d-11e6-8c40-6eba4fbe9a4c.png)

![2](https://cloud.githubusercontent.com/assets/12415700/21745981/85937920-d55d-11e6-882d-4f0f8ed5ed87.PNG)

When they are ignored the table element appears on output with the proper id but blank subtitles.

**Comment by saurabhshri** [comment]
If there's only one line in the file, it is always being ignored.

**Comment by saurabhshri** [comment]
As much as adding a whitespace or `\n` fixes this.

When files are as

**OLD**
```
Saurabh
``` 

NEW

```
Shubham
```

The **O/P** is 

```
1.


```

While if a whitespace or `\n` is added

**OLD**
```
Saurabh

```

**NEW**

```
Shubham

```

The **O/P** is :

```
1. Saurabh
   Shubham
```

**Comment by saurabhshri** [comment]
After a lot of debugging, traced the issue to `compress` function in `diff.py` ([here](https://github.com/canihavesomecoffee/sample-platform/blob/master/mod_test/nicediff/diff.py#L9)).

So here's how the function is buggy :

>The function's supposed to compress everything into a single list i.e.

```
OUTPUT is : ['I', ' ', 'love', ' ', 'apple', '\n']

 While the input is : I love apple
```
>When that newline character is removed

```
OUTSIDE rez is []

 While the S is I love apple
```

This is causing the lines to be empty.

Also the reason why this is happening is because the function is using the difference in `characters` `digits` and `other symbols` to add them to list. The current approach fails when two _similar_ (e.g. character - character) appears simultaneously.

This means in sentence 

` I love Apple`, `Apple` will be ignored.
` My number is 255 255`, `255 will be ignored.
`My number is 255 hello 255.` nothing will be ignored.

**Comment by canihavesomecoffee** [comment]
Worth 1 point for GSoC Quali.
