### ISSUE TITLE
Responsiveness of the platform - pt. 2

### ISSUE THREAD

**Issue by canihavesomecoffee** [canihavesomecoffee/sample-platform#35]
There are some smaller issues with the responsiveness of the platform:

- On mobile, the dropdown for the categories is too wide. Better styling is needed
- ~The table of latest tests isn't any good on mobile (maybe we should use a responsive table plugin?)~ (fixed in #45)
- ~Input type of login email field should be email instead of text~ (fixed in #43)

**Comment by canihavesomecoffee** [comment]
Worth 1 point for GSoC Quali.

**Comment by satyammittal** [comment]
i would like to work on issue

**Comment by canihavesomecoffee** [comment]
Just do so, and make a PR :)
