### ISSUE TITLE
Sample Platform Installation Requirements on windows Missing

### ISSUE THREAD

**Issue by satyammittal** [canihavesomecoffee/sample-platform#63]
Needs to add installation requirements of sample platform server on windows
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Sample platform commit (found at the bottom of each page) : **X.X.X**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/canihavesomecoffee/sample-platform/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/canihavesomecoffee/sample-platform/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/canihavesomecoffee/sample-platform/issues)
- [X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never visited/used the platform.
- [ ] I have used the platform just a couple of times.
- [ ] I have used the platform extensively, but have not contributed previously.
- [X] I am an active contributor to the platform.

---

{issue content here, replace this line with your issue content}

**Comment by canihavesomecoffee** [comment]
Closing this issue as you'll never fully be able to run the **entire** platform, as there's (afaik) no replacement available for KVM. Feel free to re-open if you find a drop-in replacement for KVM that offers the same performance (so no VirtualBox or alike).
